Danaswap cli
ArdanaLabs/Danaswap pull request #19
Opened 2022-10-20 18:51 UTC by marijanp

Closes

other changes

- [ ] The impure tests via `nix run .#offchain:test` were run and all are passing.
- [ ] Where applicable, grammar, punctuation, and spelling within code and comments should be plausibly correct.
- [ ] The issue(s) that the work is addressing should be linked in the PR description.
- [ ] Any significant changes beyond what's clear from the linked issue(s) are documented in the PR description

2022-10-25 18:53 UTC, Geometer1729 approved these changes
LGTM after the state->protocol refactor thing we just paired on

2022-10-27 19:34 UTC, Geometer1729 approved these changes
still LGTM

2022-10-28 18:12 UTC, epiro-ps requested changes
I'm getting the following build error on my local
```
evan@tower:~/Repos/Danaswap]$ nix build .#offchain:danaswap-cli
trace: No index state specified for haskell-project, using the latest index state that we know about (2022-06-01T00:00:00Z)!
error: builder for '/nix/store/6kbb7m6j4nn3a9mypkjfgwzxd8xdw8rk-built-deps.drv' failed with exit code 1;
       last 10 log lines:
       >   in module DanaSwap.Api
       >   at /nix/store/bz4dfsddd0s47qb2wzwjk96s08jy893f-danaswap-api-0.0.1/DanaSwap/Api.purs:56:38 - 56:54 (line 56, column 38 - line 56, column 54)
       >
       >     Unknown data constructor TransactionInput
       >
       >
       >   See https://github.com/purescript/documentation/blob/master/errors/UnknownName.md for more information,
       >   or to contribute content related to this error.
       >
       >
       For full logs, run 'nix log /nix/store/6kbb7m6j4nn3a9mypkjfgwzxd8xdw8rk-built-deps.drv'.
error: 1 dependencies of derivation '/nix/store/j1xfbw38m7gmljxd0n06anaid65b8rpa-Main-compiled-unzephyred.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l1wj3wa3a3vnygm3lcv4gws5p9hm1sm9-Main-compiled.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rna3z479yc2qxjv2i1nnmspmz5ffclxl-danaswap-cli.drv' failed to build
```

2022-10-28 18:18 UTC, marijanp commented
I know I'm working on the merge conflicts. But could you review non-runtime related code in the meantime?

2022-10-28 19:42 UTC, Geometer1729 approved these changes
LGTM yet again :+1: thanks for postponing the ctl-utils thing for me

2022-10-28 20:11 UTC, epiro-ps reviewed
What's the purpose of `offchain/danaswap-cli/fixtures/plutip/jsons`? It's currently empty save a .gitkeep.

2022-10-28 20:13 UTC, Geometer1729 commented
> What's the purpose of `offchain/danaswap-cli/fixtures/plutip/jsons`? It's currently empty save a .gitkeep.
@EvanPiro 
AFAIU It's a directory where plutip wallets are created, git doesn't track empty directories  so putting a `.gitkeep` is a common trick to get git to keep track of directories that would otherwise be empty.

2022-10-31 18:49 UTC, epiro-ps requested changes
Looks great. I tested on the `preview` network and have confirmed that [the config UTxO datum](https://preview.cexplorer.io/datum/a439cc9a99cbc5003642fd4a6d89daf493513929927ee570806cc504ccd6eba8) has the proper structure.

Just one suggestion on the CLI UX level and this is good to go on my end.

2022-10-31 19:35 UTC, marijanp commented on offchain/danaswap-cli/src/DanaSwap/Cli/Parser.purs
> +    <> help "The path to the protocol configuration file to be used (JSON). In the case of initialize this options specifies the output filepath of the initialized protocol. In every other case this
I can make it optional and then it will use the CWD and create it in there

2022-10-31 19:38 UTC, Geometer1729 commented on offchain/danaswap-cli/src/DanaSwap/Cli/Parser.purs
> +    <> help "The path to the protocol configuration file to be used (JSON). In the case of initialize this options specifies the output filepath of the initialized protocol. In every other case this
If we're going to default to that it'll probably be easiest to do that for all transactions, nothing really special about initializing.
Thought all might be none right now?

2022-10-31 19:53 UTC, epiro-ps commented on offchain/danaswap-cli/src/DanaSwap/Cli/Parser.purs
> +    <> help "The path to the protocol configuration file to be used (JSON). In the case of initialize this options specifies the output filepath of the initialized protocol. In every other case this
@Geometer1729 I agree.

2022-10-31 20:23 UTC, marijanp commented on offchain/danaswap-cli/src/DanaSwap/Cli/Parser.purs
> +    <> help "The path to the protocol configuration file to be used (JSON). In the case of initialize this options specifies the output filepath of the initialized protocol. In every other case this
Okay, the path is optional for the `initialize` command, but will be mandatory for other cases? is that behavior fine?

2022-10-31 20:29 UTC, epiro-ps commented on offchain/danaswap-cli/src/DanaSwap/Cli/Parser.purs
> +    <> help "The path to the protocol configuration file to be used (JSON). In the case of initialize this options specifies the output filepath of the initialized protocol. In every other case this
Fine with me

2022-10-31 20:57 UTC, epiro-ps approved these changes
The Cli is coming together. Fantastic work!

2022-10-31 20:57 UTC, merged